spring.application.name=risk-service
server.port=8083

patient.service.url=${PATIENT_SERVICE_URL}
notes.service.url=${NOTES_SERVICE_URL}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


jwt.secret=${JWT_SECRET}
