spring.application.name=front
server.port=8084

patient.service.url=${PATIENT_SERVICE_URL}
notes.service.url=${NOTES_SERVICE_URL}
risk.service.url=${RISK_SERVICE_URL}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


jwt.secret=${JWT_SECRET}
