spring.application.name=notes
server.port=8082

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


jwt.secret=${JWT_SECRET}
