spring.application.name=gateway

# ================================
# CONFIGURATION DU SERVEUR
# ================================
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

jwt.secret=${JWT_SECRET}